catch( AssertionError e ) {
catch( AssertionError e ) { error = null ;
catch( AssertionError e ) { error = e ;
catch( AssertionError e ) { error = error ;
catch( AssertionError e ) { error =
catch( final AssertionError e ) {
